# .github/workflows/ci.yml

name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: esocial
          POSTGRES_USER: esocial_user
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      kafka:
        image: confluentinc/cp-kafka:7.4.3
        ports:
          - 9092:9092
        options: >-
          --health-cmd "broker-api-versions --bootstrap-server localhost:9092"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and run tests
      env:
        SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/esocial
        SPRING_DATASOURCE_USERNAME: esocial_user
        SPRING_DATASOURCE_PASSWORD: secret
        SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      run: mvn clean verify
